:scrollbar:
:data-uri:
:toc2:
:linkattrs:

= bxms_decision_mgmt_foundations_lab


The following enables an decision manager execution server whose undertow web server is configured to respond to HTTP OPTION requests with CORS filters

. Initialize the template:
+
-----
$ oc create -f resources/ng-mortgage-bpmsuite70-full-mysql.yaml
-----

. Create a keystore for execution server
+
-----
$ keytool -genkey \
          -keyalg RSA \
          -alias selfsigned \
          -keystore /tmp/keystore.jks \
          -validity 360 \
          -keysize 2048 \
          -alias jboss \
          -storepass rhtgpte \
          -keypass rhtgpte \
          -dname "CN=mw,OU=gpte,O=redhat.com,L=Raleigh,S=NC,C=US"
-----

. Configure a service account that is loaded with the previously created secret:
+
-----
$  oc create serviceaccount bpmsuite-service-account
$  oc policy add-role-to-user view system:serviceaccount:jb-bpms7:bpmsuite-service-account
$  oc secrets new bpmsuite-app-secret /tmp/keystore.jks
$  oc secrets link bpmsuite-service-account bpmsuite-app-secret
-----

. Create a configmap from the JBoss CLI that enables the undertow component of the execution server with CORS:
The project template mounts a volume from this configmap to the execution server.
+
-----
$  oc create configmap undertow-cors --from-file=resources/undertow-cors.cli
-----

. Initialize OCP resources from the project template:
+
-----
$ oc new-app --name=dm-demo --template=ng-mortgage-bpmsuite70-full-mysql \
         -p IMAGE_STREAM_NAMESPACE=openshift \
         -p HTTPS_PASSWORD=rhtgpte \
         -p KIE_ADMIN_PWD=admin \
         -p APPLICATION_NAME=gpte > /tmp/gpte-dm-demo.txt
-----

. Resume DCs that are initially paused by default:
+
-----
$ oc rollout resume dc/gpte-mysql
$ oc rollout resume dc/gpte-execserv
------

. Optionally, delete all OCP resources associated with this project:
+
-----
$ oc delete all -l app=dm-demo
-----

=== Problems

. ng-mortgage build initially fails similar what is described here:  https://access.redhat.com/solutions/3009161

=== Additional Notes

-----
$ oc new-app bpmsuite70-executionserver-openshift:1.0~https://github.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab.git \
--context-dir=exec-server \
--name=exec-test
-----
