apiVersion: v1
kind: Template
labels:
  template: rhdm7-bc
  xpaas: 1.4.0
message: BuildConfig resources for Red Hat GPTE Decision Manager Foundations course
metadata:
  annotations:
    description: Application template for Red Hat JBoss Decision Management 7.0.
    iconClass: icon-jboss
    openshift.io/display-name: Red Hat Decision Manager 7.0 applications (Persistent with https)
    tags: rhdm,jboss,xpaas
    version: 1.4.0
  name: rhdm7-bc

objects:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-ng-dmf
  spec:
    nodeSelector: null
    postCommit: {}

# JA Bride / dtorresf: bumping to 2 cpu and 2Gi
# The new version of this node app has more javascript components and pre-evaluations.
# the new application has a menu for the demos and centralizes the demos for our course.
    resources:
      limits:
        cpu: "2"
        memory: 2Gi
      requests:
        cpu: "1"
        memory: 1Gi
    runPolicy: Serial
    source:
      git:
        ref: master
# dtorresf: new git repository with templated angular2 application
        uri: 'https://github.com/gpe-mw-training/gpte-ng-dmf.git'
      type: Git
    strategy:
      sourceStrategy:
        from:
# dtorresf: Using the available ImageStreamTag from the openshift registry
          kind: ImageStreamTag
          name: 'nodejs:latest'
          namespace: openshift
      type: Source
    triggers:
      - type: ImageChange
    output:
      to:
        kind: ImageStreamTag
        name: ng-dmf:latest

# JA Bride:  imagestream for custom angular app created from BC resource defined in this template
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ng-dmf
  spec:
    lookupPolicy:
      local: false



# JA Bride: Defining a BC to layer custom run script on execserv image
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-custom-execserv
  spec:
    nodeSelector: null
    postCommit: {}
    output:
      to:
        kind: ImageStreamTag
        name: custom-execserv:latest

# JA Bride:  Bumping up limit and request so tht node app builds in a timely manner without timing out
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: "1"
        memory: 1Gi


# JA Bride:  The BPM exec server build config object is comprised of the bpmsuite7 exec server layered with the source code of this project.
#            The only thing this project source code does is provide a run script to customize the standalone-openshift.xml config file of JBoss EAP.
    runPolicy: Serial
    source:
      contextDir: exec-server
      git:
        ref: master
        type: Git
        uri: https://github.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab.git
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: rhdm70-kieserver-openshift:1.0
          namespace: ${RHT_IMAGE_STREAM_NAMESPACE}
        type: Source
    triggers:
      - type: ImageChange

# JA Bride:  imagestream for customized execserv created from BC resource defined in this template
- apiVersion: v1
  kind: ImageStream
  metadata:
    labels:
      application: ${APPLICATION_NAME}
    name: custom-execserv
  spec:
    lookupPolicy:
      local: false

parameters:
- displayName: Application Name
  description: The name for the application.
  name: APPLICATION_NAME
  value: myapp
  required: true
- displayName: RHT ImageStream Namespace
  description: Namespace in which the ImageStreams for Red Hat Middleware images are
    installed. These ImageStreams are normally installed in the openshift namespace.
    You should only need to modify this if you've installed the ImageStreams in a
    different namespace/project.
  name: RHT_IMAGE_STREAM_NAMESPACE
  value: openshift
  required: true
