package com.myteam.policy_quote;

import java.util.Calendar;

function int currentYear(){
    return Calendar.getInstance().get(Calendar.YEAR);
}

rule "Newer Vehicle Surcharge"
    salience 3
	no-loop 
	lock-on-active 
    
    when
        //conditions
        $driver : Driver()
        $policy : Policy(policyType == "AUTO", vehicleYear >= currentYear()-3)
    then
        //actions
        modify($policy) {setPrice($policy.getPrice() + 100)};

end